const state={A:null,B:null,worksA:[],worksB:[],themesA:[],themesB:[],analysis:[]};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stop=new Set('the and of in for to a an on with using based from study analysis approach model models method methods applications application new via under between toward towards effects effect data results evidence research paper review journal volume issue'.split(' '));
const catalog=Array.isArray(window.RESEARCHER_CATALOG)?window.RESEARCHER_CATALOG:[];
function setStatus(t){$('status').textContent=t}
function populate(){const o=catalog.map(r=>`<option value="${esc(r.id)}">${esc(r.name)} — ${esc(r.affiliation||'')}</option>`).join('');$('selectA').insertAdjacentHTML('beforeend',o);$('selectB').insertAdjacentHTML('beforeend',o)}
function selectResearcher(side,id){const r=catalog.find(x=>x.id===id)||null;state[side]=r;const box=$(`selected${side}`);if(!r){box.className='selected-researcher empty';box.textContent='Nessun ricercatore selezionato'}else{box.className='selected-researcher';box.innerHTML=`<strong>${esc(r.name)}</strong><div class="meta">${esc(r.affiliation||'')}</div><div class="profile-description">${esc(r.description||'')}</div><div class="profile-links"><a target="_blank" rel="noopener" href="${esc(r.googleScholarUrl)}">Apri Google Scholar</a></div>`}const dup=state.A&&state.B&&state.A.id===state.B.id;$('loadThemes').disabled=!(state.A&&state.B)||dup;setStatus(dup?'Seleziona due ricercatori diversi':'Pronto');$('themeSection').classList.add('hidden');$('dashboard').classList.add('hidden')}
$('selectA').onchange=e=>selectResearcher('A',e.target.value);$('selectB').onchange=e=>selectResearcher('B',e.target.value);populate();

function parseCSV(text){const rows=[];let row=[],field='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){field+='"';i++}else if(c==='"'){q=!q}else if(c===','&&!q){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(field);if(row.some(x=>x.trim()!==''))rows.push(row);row=[];field=''}else field+=c}row.push(field);if(row.some(x=>x.trim()!==''))rows.push(row);if(!rows.length)return[];const headers=rows.shift().map(h=>h.trim().toLowerCase());return rows.map(cols=>Object.fromEntries(headers.map((h,i)=>[h,(cols[i]||'').trim()]))) }
const first=(obj,names)=>{for(const n of names){if(obj[n]!==undefined&&obj[n]!=='')return obj[n]}return''};
function normalizeWorks(rows){return rows.map((r,i)=>({id:String(i+1),title:first(r,['title','titolo']),authors:first(r,['authors','author','autori']),publication:first(r,['publication','journal','venue','rivista']),year:first(r,['year','anno']),publisher:first(r,['publisher','editore']),url:first(r,['url','link']),doi:first(r,['doi']),abstract:first(r,['abstract','summary']),source:'Google Scholar CSV'})).filter(w=>w.title)}
async function loadCSV(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`File non trovato: ${path}`);return normalizeWorks(parseCSV(await r.text()))}
function tokens(s){return (String(s||'').toLowerCase().match(/[\p{L}\p{N}-]{3,}/gu)||[]).filter(x=>!stop.has(x))}
function ngrams(s){const t=tokens(s),out=[];for(let n=1;n<=3;n++)for(let i=0;i<=t.length-n;i++)out.push(t.slice(i,i+n).join(' '));return out}
function extractThemes(works){const score=new Map();for(const w of works){const text=`${w.title} ${w.publication} ${w.abstract}`;for(const g of ngrams(text)){if(g.length<5)continue;score.set(g,(score.get(g)||0)+(g.includes(' ')?1.5:1))}}return [...score].filter(([,v])=>v>=2).sort((a,b)=>b[1]-a[1]).slice(0,16).map(([name,score])=>({name,score}))}
function renderThemes(side,themes){$(`themeName${side}`).textContent=state[side].name;$(`themes${side}`).innerHTML=themes.map((t,i)=>`<label class="theme-chip"><input type="checkbox" value="${esc(t.name)}" ${i<2?'checked':''}><span>${esc(t.name)}</span></label>`).join('');[...$(`themes${side}`).querySelectorAll('input')].forEach(x=>x.onchange=validate)}
function selected(side){return [...$(`themes${side}`).querySelectorAll('input:checked')].map(x=>x.value)}
function validate(){for(const s of ['A','B']){const a=[...$(`themes${s}`).querySelectorAll('input:checked')];if(a.length>3)a.at(-1).checked=false}const a=selected('A').length,b=selected('B').length;$('analyze').disabled=!(a&&b);$('selectionStatus').textContent=`Selezionate: ${a} + ${b}`}
$('loadThemes').onclick=async()=>{setStatus('Lettura degli snapshot Google Scholar…');$('loadThemes').disabled=true;try{[state.worksA,state.worksB]=await Promise.all([loadCSV(state.A.publicationsFile),loadCSV(state.B.publicationsFile)]);state.themesA=extractThemes(state.worksA);state.themesB=extractThemes(state.worksB);renderThemes('A',state.themesA);renderThemes('B',state.themesB);$('themeSection').classList.remove('hidden');validate();setStatus(`${state.worksA.length+state.worksB.length} pubblicazioni importate`)}catch(e){setStatus(`Errore: ${e.message}`)}finally{$('loadThemes').disabled=false}};
function evidence(works,theme){const tt=tokens(theme);return works.filter(w=>{const h=`${w.title} ${w.publication} ${w.abstract}`.toLowerCase();return tt.some(t=>h.includes(t))})}
function jaccard(a,b){const A=new Set(a),B=new Set(b),i=[...A].filter(x=>B.has(x)).length,u=new Set([...A,...B]).size;return u?i/u:0}
function keywords(wa,wb,ta,tb){const m=new Map(),add=w=>tokens(`${w.title} ${w.publication}`).forEach(x=>m.set(x,(m.get(x)||0)+1));wa.forEach(add);wb.forEach(add);tokens(`${ta} ${tb}`).forEach(x=>m.set(x,(m.get(x)||0)+4));return [...m].sort((a,b)=>b[1]-a[1]).slice(0,30)}
function makeScore(ta,tb,wa,wb){const lex=jaccard(tokens(ta),tokens(tb)),ev=Math.min(1,(wa.length+wb.length)/10),coauthors=jaccard(wa.flatMap(w=>tokens(w.authors)),wb.flatMap(w=>tokens(w.authors)));return{compatibility:Math.round(Math.min(100,25+lex*30+ev*35+coauthors*10)),novelty:Math.round(Math.max(20,90-lex*50-ev*20)),evidence:Math.round(ev*100),feasibility:Math.round(Math.min(100,35+ev*45+lex*20))}}
$('analyze').onclick=()=>{const out=[];for(const ta of selected('A'))for(const tb of selected('B')){const wa=evidence(state.worksA,ta),wb=evidence(state.worksB,tb);out.push({ta,tb,wa,wb,...makeScore(ta,tb,wa,wb),keywords:keywords(wa,wb,ta,tb)})}state.analysis=out.sort((x,y)=>y.compatibility-x.compatibility);renderDashboard()};
function renderDashboard(){const p=state.analysis,avg=k=>Math.round(p.reduce((s,x)=>s+x[k],0)/Math.max(1,p.length));$('dashboard').classList.remove('hidden');$('metrics').innerHTML=[['Compatibilità media',avg('compatibility')],['Novità media',avg('novelty')],['Forza evidenze',avg('evidence')],['Intersezioni',p.length]].map(([l,v])=>`<div class="metric"><b>${v}${l==='Intersezioni'?'':'/100'}</b><span>${l}</span></div>`).join('');const kw=new Map();p.forEach(x=>x.keywords.forEach(([k,v])=>kw.set(k,(kw.get(k)||0)+v)));const words=[...kw].sort((a,b)=>b[1]-a[1]).slice(0,30),max=words[0]?.[1]||1;$('wordCloud').innerHTML=words.map(([w,v])=>`<span style="font-size:${14+30*v/max}px;opacity:${.55+.45*v/max}">${esc(w)}</span>`).join('');$('compatibilityBars').innerHTML=p.map(x=>`<div class="bar-row"><div class="bar-label">${esc(x.ta)} × ${esc(x.tb)}</div><div class="bar-track"><div class="bar-fill" style="width:${x.compatibility}%"></div></div><div class="bar-value">${x.compatibility}</div></div>`).join('');renderRadar({Compatibilità:avg('compatibility'),Novità:avg('novelty'),Evidenze:avg('evidence'),Fattibilità:avg('feasibility'),Copertura:Math.min(100,Math.round((state.worksA.length+state.worksB.length)/.4))});$('intersectionCards').innerHTML=p.map(x=>`<div class="intersection"><h3>${esc(x.ta)} × ${esc(x.tb)}</h3><div class="score-line"><span>Compatibilità esplorativa</span><b>${x.compatibility}/100</b></div><div class="tag-row"><span class="tag">novità ${x.novelty}</span><span class="tag">evidenze ${x.evidence}</span><span class="tag">fattibilità ${x.feasibility}</span></div><div class="meta">Pubblicazioni pertinenti: ${esc(state.A.name)} ${x.wa.length} · ${esc(state.B.name)} ${x.wb.length}</div><div class="question">Segnale da approfondire leggendo abstract e testi completi dei lavori pertinenti.</div></div>`).join('');renderPapers();$('dashboard').scrollIntoView({behavior:'smooth'})}
function renderRadar(vals){const svg=$('radarChart'),cx=260,cy=180,R=120,keys=Object.keys(vals),n=keys.length,point=(r,i)=>[cx+Math.cos(-Math.PI/2+2*Math.PI*i/n)*r,cy+Math.sin(-Math.PI/2+2*Math.PI*i/n)*r];let s='';for(let g=1;g<=4;g++)s+=`<polygon points="${keys.map((_,i)=>point(R*g/4,i).join(',')).join(' ')}" fill="none" stroke="#dfe5ea"/>`;keys.forEach((k,i)=>{const q=point(R+28,i),z=point(R,i);s+=`<line x1="${cx}" y1="${cy}" x2="${z[0]}" y2="${z[1]}" stroke="#e4e9ec"/><text x="${q[0]}" y="${q[1]}" text-anchor="middle" font-size="11" fill="#65717d">${esc(k)}</text>`});s+=`<polygon points="${keys.map((k,i)=>point(R*vals[k]/100,i).join(',')).join(' ')}" fill="rgba(31,111,139,.22)" stroke="#1f6f8b" stroke-width="3"/>`;svg.innerHTML=s}
function renderPapers(){const works=[...state.worksA.map(w=>({...w,owner:state.A.name})),...state.worksB.map(w=>({...w,owner:state.B.name}))].sort((a,b)=>String(b.year).localeCompare(String(a.year)));$('papersTable').innerHTML=`<table><thead><tr><th>Ricercatore</th><th>Anno</th><th>Titolo</th><th>Autori</th><th>Pubblicazione</th></tr></thead><tbody>${works.map(w=>`<tr><td>${esc(w.owner)}</td><td>${esc(w.year||'—')}</td><td>${w.url?`<a target="_blank" rel="noopener" href="${esc(w.url)}">${esc(w.title)}</a>`:esc(w.title)}</td><td>${esc(w.authors||'—')}</td><td>${esc(w.publication||'—')}</td></tr>`).join('')}</tbody></table>`}
$('downloadJson').onclick=()=>{const payload={generatedAt:new Date().toISOString(),researchers:[{...state.A,publications:state.worksA},{...state.B,publications:state.worksB}],selectedThemes:{A:selected('A'),B:selected('B')},intersections:state.analysis.map(({wa,wb,...x})=>({...x,evidenceA:wa,evidenceB:wb}))};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`research-compatibility-${state.A.id}-${state.B.id}.json`;a.click();URL.revokeObjectURL(a.href)};

const apiBase=(window.APP_CONFIG?.AI_API_BASE||'').replace(/\/$/,'');
function aiEndpoint(){return `${apiBase}/api/analyze`}
function relevantPapersForAI(){
  const map=new Map();
  for(const x of state.analysis){
    [...x.wa,...x.wb].forEach(w=>map.set(`${w.title}|${w.authors}|${w.year}`,w));
  }
  if(!map.size)[...state.worksA.slice(0,5),...state.worksB.slice(0,5)].forEach(w=>map.set(`${w.title}|${w.authors}|${w.year}`,w));
  return [...map.values()].slice(0,10);
}
function list(items){return items?.length?`<ul>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<span class="meta">Nessun dato verificato</span>'}
function renderAI(data){
  $('aiResultsCard').classList.remove('hidden');
  const kws=(data.cross_cutting_keywords||[]).sort((a,b)=>b.weight-a.weight);
  $('aiSummary').innerHTML=`<div class="word-cloud">${kws.map(x=>`<span style="font-size:${14+Math.round(x.weight*.25)}px">${esc(x.keyword)}</span>`).join('')}</div>${data.limitations?.length?`<div class="notice"><strong>Limiti:</strong>${list(data.limitations)}</div>`:''}`;
  $('aiPaperResults').innerHTML=(data.papers||[]).map(p=>`<div class="intersection"><h3>${esc(p.title)}</h3><div class="meta">${esc(p.authors)} · ${esc(p.year)}</div><div class="ai-paper-meta"><span class="access-badge">${esc(p.match_status)}</span><span class="access-badge">${esc(p.access_level)}</span></div><strong>Keyword</strong>${list(p.keywords)}<strong>Metodi</strong>${list(p.methods)}<strong>Oggetti di studio</strong>${list(p.objects_of_study)}<strong>Risultati verificati</strong>${list(p.verified_findings)}<strong>Incertezze</strong>${list(p.uncertainties)}${p.source_urls?.length?`<strong>Fonti</strong><ul class="source-list">${p.source_urls.map(u=>`<li><a href="${esc(u)}" target="_blank" rel="noopener">${esc(u)}</a></li>`).join('')}</ul>`:''}</div>`).join('');
  $('aiCompatibility').innerHTML=(data.compatibility_signals||[]).map(x=>`<div class="intersection"><h3>${esc(x.theme_a)} × ${esc(x.theme_b)}</h3><div class="tag-row"><span class="tag">evidenza ${x.evidence_score}</span><span class="tag">novità ${x.novelty_score}</span><span class="tag">distanza ${x.methodological_distance}</span></div><strong>Paper di supporto</strong>${list(x.supporting_papers)}<div class="question">${esc(x.open_question)}</div></div>`).join('');
  $('aiResultsCard').scrollIntoView({behavior:'smooth'});
}
$('runAi').onclick=async()=>{
  const status=$('aiStatus'),papers=relevantPapersForAI();
  status.className='ai-status loading';status.textContent=`Ricerca e analisi di ${papers.length} pubblicazioni…`;$('runAi').disabled=true;
  try{
    const r=await fetch(aiEndpoint(),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({papers,themesA:selected('A'),themesB:selected('B')})});
    const data=await r.json();if(!r.ok)throw new Error(data.detail||data.error||`HTTP ${r.status}`);
    renderAI(data);status.className='ai-status success';status.textContent='Analisi completata. I livelli di accesso indicano cosa è stato realmente reperito.';
  }catch(e){status.className='ai-status error';status.textContent=`Errore: ${e.message}`}
  finally{$('runAi').disabled=false}
};
