// Generated from data/researchers.json. Do not edit this file directly.
window.RESEARCHER_CATALOG = [
  {
    "id": "daniele-angelini",
    "name": "Daniele Angelini",
    "affiliation": "Sapienza, University of Rome",
    "description": "Fractional Processes & Stochastic Calculus",
    "scholarAuthorId": "wH5FfH0AAAAJ",
    "googleScholarUrl": "https://scholar.google.com/citations?user=wH5FfH0AAAAJ&hl=it",
    "publicationsFile": "./data/scholar/daniele-angelini.csv"
  },
  {
    "id": "ivan-colagè",
    "name": "Ivan Colagè",
    "affiliation": "Pontifical University of the Holy Cross",
    "description": "Human Evolution & Cultural Transmission",
    "scholarAuthorId": "GcFlkycAAAAJ",
    "googleScholarUrl": "https://scholar.google.com/citations?user=GcFlkycAAAAJ&hl=it&oi=ao",
    "publicationsFile": "./data/scholar/ivan-colagè.csv"
  },
  {
    "id": "stefano-oliva",
    "name": "Stefano Oliva",
    "affiliation": "Università Telematica Unicusano",
    "description": "Filosofia del Linguaggio & Estetica",
    "scholarAuthorId": "65F2uicAAAAJ",
    "googleScholarUrl": "https://scholar.google.com/citations?hl=it&user=65F2uicAAAAJ",
    "publicationsFile": "./data/scholar/stefano-oliva.csv"
  },
  {
    "id": "claudio-tagliapietra",
    "name": "Claudio Tagliapietra",
    "affiliation": "Pontifical University of the Holy Cross",
    "description": "Fundamental Theology & Theology and Science",
    "scholarAuthorId": "pRI8YwkAAAAJ",
    "googleScholarUrl": "https://scholar.google.com/citations?hl=it&user=pRI8YwkAAAAJ",
    "publicationsFile": "./data/scholar/claudio-tagliapietra.csv"
  }
];
