#!/usr/bin/env python3
"""Generate the browser catalog from data/researchers.json."""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
source = ROOT / "data" / "researchers.json"
target = ROOT / "researchers.js"

researchers = json.loads(source.read_text(encoding="utf-8"))
target.write_text(
    "// Generated from data/researchers.json. Do not edit this file directly.\n"
    "window.RESEARCHER_CATALOG = "
    + json.dumps(researchers, ensure_ascii=False, indent=2)
    + ";\n",
    encoding="utf-8",
)
print(f"Generated {target.relative_to(ROOT)} with {len(researchers)} researchers")
